name: WorkloadIdentityDemo

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  ARM_TENANT_ID: geuer-pollmann.de
  ARM_CLIENT_ID: fdf939e2-e28a-4c33-a761-efa219ce9cc0
  STATE_STORAGE_ACCOUNT: tfstatechgp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        environment: azurecloud
        allow-no-subscriptions: true
        tenant-id: ${{env.ARM_TENANT_ID}}
        client-id: ${{env.ARM_CLIENT_ID}}
        audience: api://AzureADTokenExchange
    - name: Try listing containers using the CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage container list --auth-mode login --account-name "${STATE_STORAGE_ACCOUNT}"
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
